ccfldfygfddeccc

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -60,13 +60,20 @@ jobs:
       
       - name: Check if database is accessible
         run: |
-          CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db)
-          if PGPASSWORD=Ec94 psql -h $CONTAINER_IP -p 5433 -U postgres -d projecto -c "SELECT 1" > /dev/null; then
-              echo "La base de datos está accesible"
-          else
-              echo "Error: La base de datos no está accesible"
+            if docker-compose ps -q db >/dev/null; then
+              CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db)
+              if PGPASSWORD=Ec94 psql -h $CONTAINER_IP -p 5433 -U postgres -d projecto -c "SELECT 1" > /dev/null; then
+                  echo "La base de datos está accesible"
+              else
+                  echo "Error: La base de datos no está accesible"
+                  exit 1
+              fi
+            else
+              echo "Error: El contenedor de la base de datos no está en ejecución"
               exit 1
-          fi
+            fi
+        
+        
       
       
       - name: Check if tables are populated
